import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { PostComponent } from '../../shared/components/post/post.component';
import { Valid } from '../education/education-page.component';
import { TranslateModule, TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'projects-page',
  imports: [PostComponent, TranslateModule],
  templateUrl: './projects-page.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export default class ProjectsPageComponent {
  translate = inject(TranslateService)
  infos = signal<Valid[]>([
    {
      datePost: 'page_projects.one.datePost',
      imageProfile: 'assets/img/web.jpg',
      imagePost: './assets/img/cocktail.png',
      urlGitPost: 'https://github.com/naviotech/Cocktails-App',
      urlProyectPost: 'https://cocktail-app-naviotech.netlify.app/',
      containTitle: 'page_projects.one.containTitle',
      containDate: 'page_projects.one.containDate',
      containExplain: 'page_projects.one.containExplain',
      containApt: 'page_projects.one.containApt',
      containAptInfo: 'page_projects.one.containAptInfo',
      comments: 16,
      likes: 52,
      repost: 14,
      graph: 305,
    },
    {
      datePost: 'page_projects.two.datePost',
      imageProfile: 'assets/img/web.jpg',
      imagePost: './assets/img/clone.png',
      urlGitPost: 'https://github.com/naviotech/FinalWeatherApp',
      urlProyectPost: 'https://finalweatherapp-naviotech.netlify.app/',
      containTitle: 'page_projects.two.containTitle',
      containDate: 'page_projects.two.containDate',
      containExplain: 'page_projects.two.containExplain',
      containApt: 'page_projects.two.containApt',
      containAptInfo: 'page_projects.two.containAptInfo',
      comments: 14,
      likes: 28,
      repost: 9,
      graph: 114,
    },
    {
      datePost: 'page_projects.three.datePost',
      imageProfile: 'assets/img/web.jpg',
      imagePost: './assets/img/expense.png',
      urlGitPost: 'https://github.com/naviotech/expense-planner',
      urlProyectPost: 'https://expense-planner-naviotech.netlify.app/',
      containTitle: 'page_projects.three.containTitle',
      containDate: 'page_projects.three.containDate',
      containExplain: 'page_projects.three.containExplain',
      containApt: 'page_projects.three.containApt',
      containAptInfo: 'page_projects.three.containAptInfo',
      comments: 1,
      likes: 42,
      repost: 6,
      graph: 230,
    },
    {
      datePost: 'page_projects.four.datePost',
      imageProfile: 'assets/img/web.jpg',
      imagePost: './assets/img/coinmarket.png',
      urlGitPost: 'https://github.com/naviotech/CoinMarketWatch',
      urlProyectPost: 'https://shorturlapp-mayadevv.netlify.app/',
      containTitle: 'page_projects.four.containTitle',
      containDate: 'page_projects.four.containDate',
      containExplain: 'page_projects.four.containExplain',
      containApt: 'page_projects.four.containApt',
      containAptInfo: 'page_projects.four.containAptInfo',
      comments: 2,
      likes: 24,
      repost: 3,
      graph: 169,
    },
    {
      datePost: 'page_projects.five.datePost',
      imageProfile: 'assets/img/web.jpg',
      imagePost: './assets/img/ecomerce.png',
      urlGitPost: 'https://github.com/naviotech/Ecomerce',
      urlProyectPost: 'https://ecomerce-mayadevv.netlify.app/',
      containTitle: 'page_projects.five.containTitle',
      containDate: 'page_projects.five.containDate',
      containExplain: 'page_projects.five.containExplain',
      containApt: 'page_projects.five.containApt',
      containAptInfo: 'page_projects.five.containAptInfo',
      comments: 8,
      likes: 32,
      repost: 7,
      graph: 201,
    },
    {
      datePost: 'page_projects.six.datePost',
      imageProfile: 'assets/img/web.jpg',
      imagePost: './assets/img/short.png',
      urlGitPost: 'https://github.com/naviotech/ShortUrlApp',
      urlProyectPost: 'https://shorturlapp-mayadevv.netlify.app/',
      containTitle: 'page_projects.six.containTitle',
      containDate: 'page_projects.six.containDate',
      containExplain: 'page_projects.six.containExplain',
      containApt: 'page_projects.six.containApt',
      containAptInfo: 'page_projects.six.containAptInfo',
      comments: 6,
      likes: 16,
      repost: 3,
      graph: 167,
    },
  ]);
}
